// Auto-generated by scripts/translate.mjs — do not edit manually.
// Source: EN → ES  (placeholder — run DeepL script to populate)
// Re-run the script to update: DEEPL_API_KEY=xxx node scripts/translate.mjs --langs=es

export const COUNTRY_VIBES = {};
export const COUNTRY_DATA = {};
export const COUNTRY_INSIGHTS = {};
