export const USE_CASES = {
  travelers: {
    slug: 'travelers',
    emoji: '✈️',
    metaTitle: 'TerraLenses for Travelers — Compare Countries & Plan Your Next Trip',
    metaDescription: 'Planning a trip and can\'t decide between destinations? TerraLenses helps travelers compare countries, discover key facts, and plan smarter — for free.',
    h1: 'Plan Smarter Trips with Real Country Data',
    tagline: 'You\'re deciding between two destinations. You want facts, not fluff.',
    intro: 'TerraLenses gives you the data you need to make confident travel decisions — comparing countries side-by-side, exploring detailed profiles, and discovering rankings that help you pick the right destination for your style and budget.',
    useCases: [
      {
        icon: '⚖️',
        title: 'Compare two destinations before booking',
        body: 'Can\'t decide between Japan and South Korea? Greece or Italy for summer? Use the comparison tool to see climate, population, language, travel scores, and cultural highlights side by side — in seconds.',
        link: '/compare/',
        linkText: 'Open comparison tool',
      },
      {
        icon: '🗺️',
        title: 'Explore the interactive world map',
        body: 'Click any country on the globe to instantly see key facts, capitals, and travel scores. Perfect for planning multi-country trips — zoom in on a region and discover what\'s nearby.',
        link: '/map/',
        linkText: 'Explore the world map',
      },
      {
        icon: '📊',
        title: 'Discover rankings to shortlist destinations',
        body: 'Browse the world\'s most visited countries, smallest nations perfect for a quick trip, or island nations for a beach escape. Rankings make shortlisting your next destination effortless.',
        link: '/rankings/',
        linkText: 'View country rankings',
      },
      {
        icon: '📖',
        title: 'Deep dive into a country before you arrive',
        body: 'Each of our 199 country profiles includes capital city, population, languages, national dish, highest peak, major cities, and neighbouring countries — everything you need for a pre-trip briefing.',
        link: '/countries/',
        linkText: 'Browse all countries',
      },
    ],
    featuredComparisons: [
      { label: 'France vs Spain', url: '/compare/france-vs-spain/' },
      { label: 'Japan vs South Korea', url: '/compare/japan-vs-south-korea/' },
      { label: 'Italy vs Greece', url: '/compare/italy-vs-greece/' },
      { label: 'Thailand vs Vietnam', url: '/compare/thailand-vs-vietnam/' },
      { label: 'Australia vs New Zealand', url: '/compare/australia-vs-new-zealand/' },
    ],
    featuredArticles: [
      { label: 'France vs Spain: Which to Visit?', url: '/blog/france-vs-spain-which-to-visit/' },
      { label: 'Japan vs South Korea', url: '/blog/japan-vs-south-korea-travel/' },
      { label: 'Italy vs Greece for Summer', url: '/blog/italy-vs-greece-summer-holiday/' },
    ],
    cta: { text: 'Start Comparing Countries', url: '/compare/' },
    faq: [
      { q: 'How do I compare two countries on TerraLenses?', a: 'Go to the Compare page, type the names of two countries, and instantly see them side by side — including area, population, language, travel scores, and key facts. You can also go directly to /compare/france-vs-spain/ style URLs.' },
      { q: 'Does TerraLenses cover all countries in the world?', a: 'Yes — TerraLenses covers all 199 recognised sovereign states with detailed profiles including capital, population, language, national dish, highest peak, and more.' },
      { q: 'Can I use TerraLenses to find countries near a specific destination?', a: 'Yes. Each country profile includes a Neighbouring Countries section with direct links to adjacent nations — great for planning multi-country itineraries.' },
      { q: 'Are the travel scores on TerraLenses objective?', a: 'Our travel scores (Tourism, Budget, Nature, Food, Culture, Language Ease) are composite scores based on tourism data, cost of living indices, and regional averages. They\'re a useful starting guide — always cross-reference with current sources for trip planning.' },
    ],
  },

  students: {
    slug: 'students',
    emoji: '📚',
    metaTitle: 'TerraLenses for Students — Geography Research & Country Facts',
    metaDescription: 'Students use TerraLenses for geography homework, country research projects, and exploring world facts. Free, fast, and covers all 199 countries.',
    h1: 'The Geography Resource That Makes Research Effortless',
    tagline: 'You need accurate country data fast. No paywalls, no sign-ups.',
    intro: 'Whether you\'re writing a geography essay, preparing a presentation, or just curious about a country you learned about in class, TerraLenses gives you structured, reliable data on every country in the world — instantly.',
    useCases: [
      {
        icon: '📝',
        title: 'Get key facts for any country in seconds',
        body: 'Capital city, official language, population, area, currency, national sport, calling code, timezone — all on one clean page. Perfect for filling in country fact sheets or starting a research project.',
        link: '/countries/',
        linkText: 'Browse country profiles',
      },
      {
        icon: '📐',
        title: 'Compare countries for a geography assignment',
        body: 'Need to compare two countries for a class project? Our comparison tool shows both countries side-by-side with matching data categories — saves hours of cross-referencing different sources.',
        link: '/compare/',
        linkText: 'Compare two countries',
      },
      {
        icon: '🏆',
        title: 'Explore world geography rankings',
        body: 'Which is the largest country? The most populated? Which countries have the most land borders? Our rankings pages are perfect for studying world geography and answering common exam questions.',
        link: '/rankings/',
        linkText: 'View geography rankings',
      },
      {
        icon: '🌐',
        title: 'Discover countries on an interactive globe',
        body: 'Learn where countries are located relative to each other with our interactive world map. Click any country to see its facts — a great visual aid for memorising geography.',
        link: '/map/',
        linkText: 'Explore the world map',
      },
    ],
    featuredComparisons: [
      { label: 'USA vs Canada', url: '/compare/united-states-of-america-vs-canada/' },
      { label: 'India vs China', url: '/compare/india-vs-china/' },
      { label: 'Germany vs France', url: '/compare/germany-vs-france/' },
      { label: 'Brazil vs Argentina', url: '/compare/brazil-vs-argentina/' },
    ],
    featuredArticles: [
      { label: 'Germany vs Austria: Key Differences', url: '/blog/germany-vs-austria-differences/' },
      { label: 'USA vs Canada Comparison', url: '/blog/usa-vs-canada-comparison/' },
    ],
    cta: { text: 'Look Up Any Country', url: '/countries/' },
    faq: [
      { q: 'Is TerraLenses free for students?', a: 'Yes, TerraLenses is completely free to use. No account, no subscription, no paywall.' },
      { q: 'Can I cite TerraLenses as a source for school work?', a: 'TerraLenses can be used as a reference for country facts. For academic work, we recommend also citing primary sources such as the UN, World Bank, or national statistical offices for key figures.' },
      { q: 'How many countries does TerraLenses cover?', a: 'TerraLenses covers all 199 recognised sovereign states with detailed profiles.' },
      { q: 'Can I compare more than two countries at once?', a: 'Currently TerraLenses supports head-to-head comparisons of two countries at a time. You can run multiple comparisons to build a broader picture.' },
    ],
  },

  teachers: {
    slug: 'teachers',
    emoji: '🏫',
    metaTitle: 'TerraLenses for Teachers — Interactive Geography for the Classroom',
    metaDescription: 'Teachers use TerraLenses to make geography lessons engaging: interactive maps, country comparisons, and rankings for classroom activities covering 199 countries.',
    h1: 'Bring Geography to Life in Your Classroom',
    tagline: 'An interactive, visual geography tool your students will actually enjoy using.',
    intro: 'TerraLenses gives teachers a free, browser-based tool for geography lessons — an interactive world map, side-by-side country comparisons, and rankings that turn abstract geography into concrete, visual learning.',
    useCases: [
      {
        icon: '🌍',
        title: 'Interactive world map for visual learning',
        body: 'Project the TerraLenses world map in class and click through countries with your students. Each click reveals the capital, population, language, and key facts — perfect for whole-class learning or individual exploration.',
        link: '/map/',
        linkText: 'Open the world map',
      },
      {
        icon: '⚔️',
        title: 'Country comparison for debate activities',
        body: 'Divide the class into groups, assign each group two countries, and ask them to argue which is better for tourism, economic development, or quality of life using the comparison tool. Encourages critical thinking with real data.',
        link: '/compare/',
        linkText: 'Try a country comparison',
      },
      {
        icon: '🏆',
        title: 'Rankings for geography quizzes',
        body: 'Use our "Largest Countries", "Most Populated", and "Most Land Borders" rankings as the basis for classroom geography quizzes. Ask students to predict the rankings before revealing the answers.',
        link: '/rankings/',
        linkText: 'View all rankings',
      },
      {
        icon: '🗂️',
        title: 'Country profiles for research projects',
        body: 'Assign students a country profile to research — they can find capital city, language, national dish, highest peak, and neighbours all in one place. A great starting point for a country presentation.',
        link: '/countries/',
        linkText: 'Browse country profiles',
      },
    ],
    featuredComparisons: [
      { label: 'Russia vs Canada (largest countries)', url: '/compare/russia-vs-canada/' },
      { label: 'India vs China (most populated)', url: '/compare/india-vs-china/' },
      { label: 'France vs Germany', url: '/compare/france-vs-germany/' },
    ],
    featuredArticles: [
      { label: 'Australia vs New Zealand', url: '/blog/australia-vs-new-zealand-travel/' },
      { label: 'Japan vs South Korea', url: '/blog/japan-vs-south-korea-travel/' },
    ],
    cta: { text: 'Open the World Map', url: '/map/' },
    faq: [
      { q: 'Does TerraLenses work on classroom projectors and tablets?', a: 'Yes. TerraLenses is fully responsive and works on any device with a modern browser — desktops, tablets, and smartphones. The interactive map is particularly effective on large displays.' },
      { q: 'Is TerraLenses free for classroom use?', a: 'Completely free. No registration required, no per-student licensing, no premium features behind a paywall.' },
      { q: 'What age range is TerraLenses suitable for?', a: 'TerraLenses is suitable for secondary school students (ages 11+) and above. The data is presented clearly and the interface is intuitive enough for most students to navigate independently.' },
      { q: 'Can students access TerraLenses for homework?', a: 'Yes. Share any TerraLenses URL with students — country profiles, comparison pages, or the map — and they can access it from any device at home.' },
    ],
  },

  'trivia-lovers': {
    slug: 'trivia-lovers',
    emoji: '🧠',
    metaTitle: 'TerraLenses for Trivia Lovers — World Geography Facts & Rankings',
    metaDescription: 'Love geography trivia? TerraLenses has rankings, surprising country facts, and head-to-head comparisons across 199 countries. Feed your curiosity.',
    h1: 'Feed Your Geography Curiosity with 199 Countries of Data',
    tagline: 'Which country has the most land borders? The smallest capital city? You\'ll find out.',
    intro: 'TerraLenses is a geography enthusiast\'s playground — unexpected rankings, surprising country facts, and the ability to compare any two countries on the planet. Prepare to go down a rabbit hole.',
    useCases: [
      {
        icon: '🏅',
        title: 'Explore surprising world rankings',
        body: 'Which is the world\'s smallest country? Which nation has the most land borders? The most populated? Our rankings reveal the geography facts that stump even avid quizzers.',
        link: '/rankings/',
        linkText: 'Explore rankings',
      },
      {
        icon: '🆚',
        title: 'Settle geographical debates',
        body: 'Is Australia bigger than Europe? Is Russia\'s population higher than Canada\'s? The comparison tool puts any two countries side by side so you can settle bar trivia once and for all.',
        link: '/compare/',
        linkText: 'Compare any two countries',
      },
      {
        icon: '🏝️',
        title: 'Discover island nations',
        body: 'From Nauru (the world\'s smallest island nation) to Indonesia (with 17,000 islands), our island nations ranking covers every country entirely surrounded by sea.',
        link: '/rankings/island-nations/',
        linkText: 'View island nations',
      },
      {
        icon: '🌏',
        title: 'Explore lesser-known countries',
        body: 'How much do you know about Palau, São Tomé and Príncipe, or Nauru? Click any country on the map or browse the full list to discover the world\'s most obscure nations.',
        link: '/countries/',
        linkText: 'Browse all 199 countries',
      },
    ],
    featuredComparisons: [
      { label: 'Vatican City vs Nauru (smallest countries)', url: '/compare/vatican-city-vs-nauru/' },
      { label: 'Russia vs Antarctica', url: '/compare/russia-vs-canada/' },
      { label: 'Monaco vs Liechtenstein', url: '/compare/monaco-vs-liechtenstein/' },
    ],
    featuredArticles: [
      { label: 'Thailand vs Vietnam', url: '/blog/thailand-vs-vietnam-backpacking/' },
      { label: 'Australia vs New Zealand', url: '/blog/australia-vs-new-zealand-travel/' },
    ],
    cta: { text: 'Explore Country Rankings', url: '/rankings/' },
    faq: [
      { q: 'What is the world\'s smallest country?', a: 'Vatican City, with an area of just 0.44 km² and a population of around 800. It is an independent city-state within Rome, Italy. See it in our smallest countries ranking.' },
      { q: 'Which country has the most land borders?', a: 'China and Russia are tied — both share land borders with 14 other countries. See the full ranking on our Most Land Borders page.' },
      { q: 'What is the world\'s largest country by area?', a: 'Russia, at 17,098,242 km² — nearly twice the size of the second-largest country, Canada. It covers about 11% of the Earth\'s total land surface.' },
      { q: 'How many island nations are there?', a: 'There are approximately 47 countries that are entirely surrounded by water with no land borders. These include Japan, Australia, Iceland, Cuba, and many Pacific island nations.' },
    ],
  },

  expats: {
    slug: 'expats',
    emoji: '🏡',
    metaTitle: 'TerraLenses for Expats — Compare Countries Before You Move',
    metaDescription: 'Considering moving abroad? TerraLenses helps expats compare countries on key metrics — language, region, neighbours, and more — before making the big decision.',
    h1: 'Compare Countries Before Making the Move',
    tagline: 'Relocating is a big decision. Start with data, not guesswork.',
    intro: 'TerraLenses helps expats and digital nomads research potential new home countries — comparing key facts, understanding regional context, and exploring neighbouring countries to build a complete picture before committing.',
    useCases: [
      {
        icon: '⚖️',
        title: 'Compare your top two destinations side by side',
        body: 'Portugal vs Spain? Thailand vs Malaysia? Put your two finalists in the comparison tool and see language, region, population density, and travel scores side by side — a useful first filter.',
        link: '/compare/',
        linkText: 'Compare destinations',
      },
      {
        icon: '🌐',
        title: 'Research neighbouring countries for regional context',
        body: 'If you\'re moving to a new region, understanding the neighbourhood matters. Each country profile shows all neighbouring countries with direct links — build a mental map of the region before you arrive.',
        link: '/countries/',
        linkText: 'Explore country profiles',
      },
      {
        icon: '📖',
        title: 'Read expert expat comparison guides',
        body: 'Our blog covers expat-specific comparisons in depth — cost of living, visa routes, language integration, and quality of life factors across the most popular expat destinations.',
        link: '/blog/portugal-vs-spain-expat/',
        linkText: 'Read Portugal vs Spain for Expats',
      },
      {
        icon: '🗺️',
        title: 'Visualise where countries sit globally',
        body: 'Use the interactive map to understand time zones, proximity to home, and regional context. Crucial for remote workers managing cross-continental meetings.',
        link: '/map/',
        linkText: 'Open the world map',
      },
    ],
    featuredComparisons: [
      { label: 'Portugal vs Spain', url: '/compare/portugal-vs-spain/' },
      { label: 'Thailand vs Malaysia', url: '/compare/thailand-vs-malaysia/' },
      { label: 'Germany vs Netherlands', url: '/compare/germany-vs-netherlands/' },
      { label: 'Mexico vs Colombia', url: '/compare/mexico-vs-colombia/' },
    ],
    featuredArticles: [
      { label: 'Portugal vs Spain for Expats', url: '/blog/portugal-vs-spain-expat/' },
      { label: 'Australia vs New Zealand', url: '/blog/australia-vs-new-zealand-travel/' },
    ],
    cta: { text: 'Start Comparing Countries', url: '/compare/' },
    faq: [
      { q: 'Does TerraLenses show cost of living data?', a: 'TerraLenses shows relative travel budget scores and key economic indicators as part of country comparisons. For detailed cost of living data (rent prices, grocery costs), we recommend Numbeo or Expatistan alongside TerraLenses.' },
      { q: 'Which countries are most popular with expats?', a: 'Popular expat destinations include Portugal (D7 visa, mild climate, affordability), Spain (Beckham Law, beach lifestyle), Thailand (low cost, digital nomad community), Mexico (proximity to USA, low cost), and Germany (strong job market, EU access). Read our Portugal vs Spain expat guide for a detailed comparison.' },
      { q: 'Can I use TerraLenses to find countries with easy visa access?', a: 'TerraLenses provides country profiles and comparisons but does not include real-time visa data. For visa requirements, check the official government source or services like iVisa or VisaHQ.' },
      { q: 'How do I use TerraLenses to research a region?', a: 'Start with a country profile for your target country — the Neighbouring Countries section links to all adjacent nations. Use the comparison tool to compare your top choices. Browse our blog for expat-focused articles on specific country pairs.' },
    ],
  },

  researchers: {
    slug: 'researchers',
    emoji: '🔬',
    metaTitle: 'TerraLenses for Researchers — World Country Data & Geographic Statistics',
    metaDescription: 'Researchers and journalists use TerraLenses for quick country data lookups, geographic comparisons, and population/area statistics across 199 countries.',
    h1: 'Reliable Country Data for Research and Analysis',
    tagline: 'Fast access to structured geographic data across 199 countries.',
    intro: 'TerraLenses provides researchers, journalists, and analysts with structured, consistent data on every sovereign state — population, area, capital, language, regional classification, and neighbouring countries — in a browsable, comparable format.',
    useCases: [
      {
        icon: '📊',
        title: 'Quick country fact lookup',
        body: 'Need the capital of Equatorial Guinea? The population of San Marino? The official language of Timor-Leste? Each of our 199 country profiles gives you structured key facts in seconds — no sign-up required.',
        link: '/countries/',
        linkText: 'Browse all countries',
      },
      {
        icon: '📏',
        title: 'Compare country metrics side by side',
        body: 'The comparison tool puts any two countries\' data in a structured table — area, population, language, regional classification, travel scores, and more. Useful for illustrating differences in data journalism.',
        link: '/compare/',
        linkText: 'Open comparison tool',
      },
      {
        icon: '🗂️',
        title: 'Explore geographic rankings',
        body: 'Sorted lists of countries by area (largest/smallest), population, and number of land borders. Useful for contextualising statistics in reports — e.g. "the X largest countries account for Y% of global land area."',
        link: '/rankings/',
        linkText: 'View rankings',
      },
      {
        icon: '🌐',
        title: 'Visualise geographic context',
        body: 'The interactive world map provides spatial context for any analysis involving country locations, regional groupings, or neighbouring state relationships.',
        link: '/map/',
        linkText: 'Open the world map',
      },
    ],
    featuredComparisons: [
      { label: 'India vs China (largest populations)', url: '/compare/india-vs-china/' },
      { label: 'Russia vs Canada (largest areas)', url: '/compare/russia-vs-canada/' },
      { label: 'USA vs Brazil', url: '/compare/united-states-of-america-vs-brazil/' },
    ],
    featuredArticles: [
      { label: 'USA vs Canada Comparison', url: '/blog/usa-vs-canada-comparison/' },
      { label: 'Germany vs Austria', url: '/blog/germany-vs-austria-differences/' },
    ],
    cta: { text: 'Browse Country Data', url: '/countries/' },
    faq: [
      { q: 'What data sources does TerraLenses use?', a: 'TerraLenses draws from publicly available geographic and demographic data including the UN, World Bank, and national statistical sources. Data is updated periodically — for time-sensitive research, always verify figures against primary sources.' },
      { q: 'Can I download or export country data from TerraLenses?', a: 'Currently, TerraLenses does not offer bulk data export. Data is presented in browsable pages and comparison tables. For bulk geographic data, sources like the World Bank Open Data or UN Data are recommended.' },
      { q: 'How does TerraLenses define "country"?', a: 'TerraLenses covers 199 recognised sovereign states based on UN member status and widely recognised de-facto independent nations. Territories, dependencies, and disputed regions are generally not included as separate profiles.' },
      { q: 'How often is the data updated?', a: 'Country data on TerraLenses is reviewed and updated periodically. Population figures reflect recent census and estimate data. For the most current statistics, cross-reference with Worldometers, the World Bank, or the CIA World Factbook.' },
    ],
  },
};

export const USE_CASE_SLUGS = Object.keys(USE_CASES);
