"New Zealand": {
  capital: "Wellington perches at the southern tip of the North Island, its steep hillside suburbs connected by the iconic red cable car — a city where the Museum of New Zealand Te Papa Tongarewa anchors a waterfront that punches far above its modest size.",
  people: "New Zealanders navigate identity through the Treaty of Waitangi, and the Māori concept of manaakitanga — hospitality and respect for others — genuinely shapes how strangers are treated, from rural marae to city streets.",
  sport: "The All Blacks' haka, Ka Mate, performed before every test match, is not ceremonial theatre but a living war challenge rooted in the survival story of Ngāti Toa chief Te Rauparaha, making rugby here an act of cultural declaration.",
  nature: "The Southern Alps spine the South Island with 3,000-metre peaks, permanent glaciers like Franz Josef that descend into temperate rainforest, and a geological restlessness that reminds residents the land itself is still being made."
},
"Nigeria": {
  capital: "Abuja was purpose-built in the 1980s to replace Lagos as a neutral federal capital, its modernist grid designed by Japanese architect Kenzo Tange, and the copper-domed Aso Rock Villa sits beneath a 400-metre granite monolith that dominates the skyline.",
  people: "Nigeria's 250-plus ethnic groups each maintain distinct traditions, yet Lagos has forged Afrobeats into a global export — musicians like Fela Kuti and, later, Burna Boy made Nigerian popular identity as much sonic as tribal.",
  food: "Jollof Rice is the subject of fierce West African rivalry — the Nigerian version, cooked over open flame in a heavy pot to achieve the prized smoky bottom layer called 'party jollof', is claimed as the definitive original and the dish anchors every major celebration from naming ceremonies to state weddings.",
  sport: "The Super Eagles' 1994 Africa Cup of Nations victory and their debut World Cup knockout-stage run that same year, defeating Bulgaria and pushing Italy to extra time, announced Nigeria as a continental football force that has since produced a continuous pipeline of Premier League talent.",
  nature: "The Niger Delta is one of the world's most biodiverse wetland systems, a maze of creeks, mangroves and barrier islands stretching across 20,000 square kilometres — a landscape whose oil wealth and ecological fragility have defined Nigeria's modern political struggle."
},
"North Korea": {
  capital: "Pyongyang is one of the world's most deliberately designed capitals — Kim Il-sung ordered its reconstruction after the Korean War as a showcase socialist city, producing the 170-metre Juche Tower, the Ryugyong Hotel's unfinished pyramid, and wide boulevards built for mass pageantry rather than pedestrian life.",
  people: "North Koreans participate in the Mass Games, Arirang — a choreographed performance involving up to 100,000 citizens that produces human mosaics visible from the stadium's opposite stand, a display of collective precision with no modern parallel.",
  sport: "North Korea's 1966 World Cup squad, entirely unknown outside the country, defeated Italy 1–0 and reached the quarter-finals in England, a result still celebrated domestically as proof of Juche self-reliance and never officially explained by the Italian Football Federation.",
  nature: "Paektu Mountain, a 2,744-metre volcanic peak straddling the Chinese border, holds a crater lake called Heaven Lake and sits at the ideological core of Korean mythology — the regime claims Kim Jong-il was born on its slopes, binding geography to dynastic legitimacy."
},
"Norway": {
  capital: "Oslo rebuilt its waterfront around the Oslofjord with the Snøhetta-designed Opera House, whose sloping white marble roof invites the public to walk to the water's edge — a building that single-handedly shifted the city's relationship with its own shoreline.",
  people: "Norwegians observe Friluftsliv — a philosophical commitment to outdoor life in all seasons that predates the word coined by playwright Henrik Ibsen in 1859 — meaning ski tracks are groomed through city parks and office workers take lunch hikes as a matter of routine.",
  sport: "Norway has won more Winter Olympic medals than any other nation, but cross-country skiing carries a near-religious status: the Holmenkollen Ski Festival, held outside Oslo since 1892, draws 50,000 spectators to watch what is effectively a national communion with snow.",
  nature: "The western fjords — Sognefjord reaches 204 kilometres inland and 1,308 metres deep — were carved by glaciers retreating 10,000 years ago and remain the geological fact that shaped Norwegian settlement, fishing, shipping and the entire national aesthetic."
},
"Pakistan": {
  capital: "Islamabad was carved out of the Pothohar Plateau in the 1960s to replace Karachi as capital, designed by Greek firm Doxiadis Associates on a modular grid, and the Faisal Mosque — paid for by Saudi Arabia and completed in 1986 — holds 100,000 worshippers beneath a tent-shaped shell that became the country's most recognisable silhouette.",
  people: "Hospitality in Pakistan carries the weight of obligation — the Pashtun code of Pashtunwali demands that even a stranger requesting refuge must be protected and fed, a tradition that extends in softened form across most of the country's regional cultures.",
  sport: "Pakistan's 1992 Cricket World Cup victory under Imran Khan, won with a squad that had lost early matches and nearly been eliminated, produced a redemption narrative that Khan later translated directly into a political career, making cricket and national identity inseparable.",
  nature: "The Karakoram range contains five of the world's seventeen peaks above 8,000 metres, including K2, whose near-vertical faces and lethal weather make it statistically more dangerous to summit than Everest — a landscape so extreme it has no permanent human habitation above its base camps."
},
"Peru": {
  capital: "Lima's Historic Centre, a UNESCO World Heritage Site, contains some of the finest Spanish colonial baroque architecture in the Americas, including the Cathedral built over an Inca palace — but the city is equally defined by its Pacific clifftop district of Miraflores, where paragliders launch over the ocean.",
  people: "Peruvians maintain a dual cosmology in which Andean spiritual practices — offerings to Pachamama, divination with coca leaves — coexist with Catholicism in a syncretism refined over 500 years of negotiated belief.",
  food: "Ceviche has been prepared on Peru's Pacific coast for at least 2,000 years, with pre-Inca peoples marinating fish in tumbo fruit juice — the Spanish later introduced lime — and today Lima's ceviché bars are considered serious culinary destinations, with the dish officially designated as cultural heritage by the Peruvian government.",
  sport: "Peru's greatest footballing moment remains Teófilo Cubillas at the 1970 and 1978 World Cups — his thunderous free-kicks against Scotland in 1978 made him one of the tournament's all-time top scorers and still carry the weight of a golden era the country has spent decades trying to recapture.",
  nature: "The Amazon Basin covers 60 percent of Peru's territory, and the Madre de Dios region contains some of the planet's highest documented biodiversity — Manu National Park alone holds more bird species than the entire continental United States."
},
"Philippines": {
  capital: "Manila's walled colonial district of Intramuros, built by the Spanish in 1571 on the banks of the Pasig River, survived centuries of occupation but was nearly obliterated in World War II's Battle of Manila — its restoration is an ongoing act of archaeological retrieval in a city otherwise defined by unrelenting density.",
  people: "Filipinos practise bayanihan — a tradition of communal labour, once literally neighbours carrying a house together to a new site — and the spirit persists in disaster responses and overseas worker networks that collectively remit over $30 billion annually back to the archipelago.",
  sport: "Manny Pacquiao's eight world titles across eight weight divisions made him the only boxer to achieve that distinction, and his bouts against De La Hoya, Hatton and Cotto were national events that emptied Philippine streets as thoroughly as any typhoon curfew.",
  nature: "The Philippine Archipelago comprises 7,641 islands stretched across 1,800 kilometres, with the Tubbataha Reef in the Sulu Sea — accessible only by liveaboard and only for a few months a year — protecting one of the last near-pristine coral triangle ecosystems on the planet."
},
"Poland": {
  capital: "Warsaw's Old Town is a meticulous postwar reconstruction — the entire historic centre was systematically destroyed by Nazi forces in 1944, then rebuilt from 18th-century Canaletto paintings, making it arguably the world's most precisely documented act of architectural resurrection, now a UNESCO World Heritage Site.",
  people: "Polish café culture revolves around the kawiarnia as a place of extended intellectual and social exchange — a tradition stretching from the literary cafes of interwar Kraków to the Solidarity-era underground press meetings that helped dismantle communism.",
  sport: "Poland's volleyball programme has won the FIVB World Championship three times, producing players like Bartosz Kurek and Wilfredo León, and the national team's 2014 and 2018 victories were celebrated with the same civic intensity Poles normally reserve for papal visits and European Championship qualification.",
  nature: "Białowieża Forest, straddling the Polish-Belarusian border, is the last primeval lowland forest in Europe — home to the continent's largest land mammal, the European bison, hunted to extinction in the wild and reintroduced here from zoo stock in the 1950s."
},
"Portugal": {
  capital: "Lisbon is built across seven hills over the Tagus estuary, its yellow trams climbing gradients that defeat most cities, and the Alfama district — largely spared by the 1755 earthquake that levelled the rest — preserves a medieval street pattern that Moorish residents would still recognise.",
  people: "Saudade, the Portuguese word for a melancholic longing for something absent or lost, is not merely a poetic conceit — it structures fado music, informs attitudes toward the colonial past, and appears in casual conversation as a genuine emotional reference point unavailable in other languages.",
  food: "Bacalhau — salt cod — arrived in Portuguese kitchens in the 15th century when Newfoundland fishing fleets needed protein that could survive months at sea, and its 365 claimed recipes reflect the ingenuity of a cuisine built on dried preservation: from the creamy Bacalhau com Natas to the simple Bacalhau à Brás of shredded cod and scrambled egg.",
  sport: "Eusébio da Silva Ferreira, born in Mozambique and shaped by Benfica, finished top scorer at the 1966 World Cup with nine goals, becoming Portugal's first football icon in a moment that also crystallised the complex relationship between the national team and the Lusophone world.",
  nature: "The Azores archipelago, rising from the Mid-Atlantic Ridge 1,500 kilometres offshore, sits on the junction of three tectonic plates — its volcanic lakes, whale migration routes and cloud-forest summits constitute a Portugal that most of the mainland has never visited."
},
"Romania": {
  capital: "Bucharest contains the Palace of the Parliament — the world's second largest administrative building by volume, constructed by Nicolae Ceaușescu at enormous human cost in the 1980s by demolishing a fifth of the historic city — a building so vast that sections remain unfurnished decades after his execution.",
  people: "Romanian folk embroidery, the ie blouse with its regional geometric patterns, carries enough cultural significance that it inspired Henri Matisse's La Blouse Roumaine of 1940 — and the garment has undergone a genuine grassroots revival among young Romanians since the 2010s.",
  sport: "Nadia Comaneci's perfect 10 at the 1976 Montreal Olympics — the first in gymnastics history, awarded to a 14-year-old from Onești — was so unprecedented that the scoreboard could only display 1.00, and the moment remains the defining image of Romanian sporting achievement.",
  nature: "The Danube Delta, where Europe's second-longest river fragments into 300 channels before reaching the Black Sea, is one of the continent's most important wetland ecosystems — home to 300 bird species and European populations of pelicans that were nearly extinct elsewhere."
},
"Russia": {
  capital: "Moscow's seven Stalinist skyscrapers — the so-called Seven Sisters built between 1947 and 1953 — still dominate the skyline with their wedding-cake silhouettes and spired towers, a deliberate architectural intimidation that Soviet planners designed to outscale any Western capital.",
  people: "Russians maintain a sharp distinction between public behaviour — reserved, formal, avoiding eye contact with strangers — and the intense warmth extended to those admitted to the domestic circle, a duality shaped by centuries of navigating surveillance and collective mistrust of institutions.",
  sport: "Soviet and Russian ice hockey produced the Red Machine: between 1954 and 1991 the USSR won seven Olympic gold medals and dominated the World Championship, and the 1972 Summit Series against Canada — won by the Soviets in points terms — remains the sport's defining ideological confrontation.",
  nature: "Lake Baikal contains 20 percent of the world's unfrozen surface fresh water, reaches 1,642 metres deep, and hosts the nerpa — the world's only exclusively freshwater seal species — a geological relic so ancient that it functions as a separate evolutionary laboratory."
},
"Saudi Arabia": {
  capital: "Riyadh's transformation from a small walled oasis town into a 7-million-person metropolitan sprawl occurred almost entirely between 1950 and 2000, funded by oil revenues that produced the Kingdom Centre tower's sky bridge and a skyline assembled with unusual speed from global architectural catalogues.",
  people: "Saudi hospitality centres on the ritual of Arabic coffee, qahwa — brewed with cardamom and saffron and poured from a long-spouted dallah — which a host refills continuously until the guest signals sufficiency by tilting the cup, an exchange with specific social grammar that predates oil wealth by centuries.",
  food: "Kabsa, the national rice dish of long-grain rice cooked in a broth of lamb or chicken with black lime, cardamom, cloves and rose water, originated in the Najd region and travels with Saudi diaspora communities as the meal that collapses time and geography back to a particular grandmother's kitchen.",
  sport: "Saudi Arabia's 2–1 defeat of Argentina at the 2022 World Cup in Qatar — while Lionel Messi's team was ranked third in the world — produced scenes of spontaneous street celebration across the kingdom and a government-declared national holiday the following morning.",
  nature: "The Rub' al Khali, the Empty Quarter, is the world's largest continuous sand desert — 650,000 square kilometres of dune fields reaching 250 metres in height — a landscape so inhospitable that it remained unsurveyed by Westerners until Wilfred Thesiger's crossings in 1946 and 1947."
},
"Senegal": {
  capital: "Dakar occupies the westernmost point of the African continent on the Cap-Vert peninsula, and its position as the Atlantic terminus of the Paris-Dakar Rally between 1979 and 2007 made it globally recognisable — though the race's cultural imposition eventually ended its welcome.",
  people: "The Mouride Brotherhood, a Sufi Islamic order founded in Senegal in 1883 by Cheikh Ahmadou Bamba, commands the loyalty of millions and runs a parallel economy centred on the holy city of Touba — a faith community with its own internal governance that negotiates directly with the Senegalese state.",
  sport: "Senegalese traditional wrestling, Laamb, packs stadiums in Dakar with crowds comparable to football finals — champion wrestlers like Balla Gaye 2 and Bombardier are national celebrities whose bouts draw corporate sponsorship and hours of television coverage, predating football as the country's defining sporting spectacle.",
  nature: "The Sine-Saloum Delta, where the Saloum River dissolves into mangrove channels and tidal islands before reaching the Atlantic, supports populations of dolphins, manatees and more than 200 bird species — a waterscape that has shaped the fishing communities of the Serer people for a thousand years."
},
"Serbia": {
  capital: "Belgrade sits at the confluence of the Sava and Danube rivers — a strategic position that has made it one of the most frequently besieged cities in European history, captured and destroyed over 40 times — and the Kalemegdan fortress at that junction now operates as a public park where families walk above the walls that centuries of armies failed to hold permanently.",
  people: "Serbs observe Slava, the celebration of a family's patron saint passed from father to son across generations — a practice unique to Serbian Orthodoxy in which each household maintains its own liturgical calendar date, making January through December a continuous procession of family-specific religious feasts.",
  sport: "Novak Djokovic's 24 Grand Slam singles titles — more than any player in tennis history — have turned a country with no prior tennis tradition into a nation that fills Belgrade's Tašmajdan Stadium for Davis Cup ties and names its airport after him.",
  nature: "The Tara mountain plateau in western Serbia contains Perućac Lake, deep canyons of the Drina River, and the last remaining stands of Pančić's spruce — a tree rediscovered in the 1870s after being thought extinct, now protected in a national park that constitutes one of central Europe's most intact forest ecosystems."
},
"Singapore": {
  capital: "Singapore is simultaneously city, capital and entire nation-state — the Gardens by the Bay Supertrees and the Marina Bay Sands SkyPark define a skyline assembled in less than 60 years from reclaimed land, a deliberate global-stage architectural statement by a government that treats urban design as national branding.",
  people: "Singapore's four official languages — English, Mandarin, Malay and Tamil — coexist with Singlish, the creole tongue that fuses all four with Hokkien and Cantonese particles, and which the government has periodically tried to suppress while Singaporeans stubbornly maintain it as the truest marker of local belonging.",
  food: "Hainanese Chicken Rice arrived in Singapore with immigrants from Hainan Province in the early 20th century and was refined by hawker stall operators into a dish of such precision — the rice cooked in chicken fat and pandan, the bird poached to silk — that it became the unofficial national meal and the subject of Michelin recognition at hawker-centre price points.",
  sport: "Joseph Schooling's 100m butterfly gold at the 2016 Rio Olympics — defeating his childhood idol Michael Phelps in a world-record-equalling time — was Singapore's first Olympic gold in any sport and produced a reception at Changi Airport that brought tens of thousands into the arrivals hall.",
  nature: "Despite being the world's most densely developed city-state, Singapore retains Bukit Timah Nature Reserve — a patch of primary rainforest within the city limits holding more tree species than the entire North American continent — a deliberate conservation choice that defines Singapore's self-image as a City in a Garden."
},
"South Africa": {
  capital: "South Africa has three capitals dividing legislative, executive and judicial functions between Pretoria, Cape Town and Bloemfontein — an arrangement dating from the compromises of the 1910 Act of Union — making Pretoria's Union Buildings, designed by Herbert Baker and set on an amphitheatre of terraced gardens, the seat of presidential power in a country that also holds parliamentary sessions 1,400 kilometres away.",
  people: "South Africa's 11 official languages include Zulu, Xhosa, Afrikaans and eight others, and the country's negotiated transition from apartheid produced a constitutional architecture that the post-colonial world has studied as a model of managed transformation.",
  sport: "The Springboks' 1995 Rugby World Cup victory on home soil, with Nelson Mandela presenting the trophy to captain Francois Pienaar wearing jersey number 6, was a moment of such calculated symbolic weight — Mandela had worn the same jersey — that it was credited with temporarily unifying a country still raw from apartheid.",
  nature: "The Cape Floristic Region around the Western Cape is one of six global floral kingdoms and the smallest, yet contains over 9,000 plant species — more per square kilometre than the Amazon — including fynbos, a shrubland that requires periodic fire to regenerate and exists nowhere else on Earth."
},
"South Korea": {
  capital: "Seoul was rebuilt almost entirely after the Korean War left it in ruins in 1953 and now houses half the national population in a metropolitan area of 25 million — yet the Bukchon Hanok Village preserves a neighbourhood of 600-year-old tile-roofed hanok houses within walking distance of the glass towers of Gangnam.",
  people: "South Koreans have industrialised the concept of education to the degree that the university entrance exam, the Suneung, halts air traffic over Seoul to prevent noise during the listening section — a national pause in which even the military reschedules exercises around a single test day.",
  food: "Kimchi — fermented cabbage or radish with chilli, garlic and ginger — has been prepared in the Korean peninsula for over 2,000 years, and the kimjang tradition of communal winter fermentation was added to UNESCO's Intangible Cultural Heritage list in 2013, recognising it as a social practice as much as a culinary one.",
  sport: "Taekwondo was codified in South Korea in the 1950s partly as a nationalist project to distinguish Korean martial arts from Japanese karate after the colonial period, and its 1988 Seoul Olympics debut as a demonstration sport — on home soil — completed its transformation from regional tradition to global discipline.",
  nature: "Jeju Island, a volcanic shield island off the southern coast, rises to the 1,950-metre Hallasan crater, contains lava tube caves extending nine kilometres underground, and is home to the haenyeo — women free-divers who have harvested the seabed without equipment for over 1,500 years."
},
"Spain": {
  capital: "Madrid became Spain's capital in 1561 when Philip II chose it for its central geography rather than any prior grandeur, and the Prado Museum — containing Velázquez's Las Meninas and Goya's Black Paintings — is housed in a building originally designed as a natural history museum, an accident of repurposing that produced one of Europe's great art institutions.",
  people: "Spaniards observe the sobremesa — the extended period of conversation after a meal when the table is not cleared and no one leaves — as a social institution so entrenched that business lunches routinely run three hours and the concept of rushing a meal is treated as a minor social failure.",
  food: "Paella originated in the Valencia region as a midday meal for agricultural workers, cooked over wood fire with rabbit, snails and whatever vegetables the season offered — the seafood version now ubiquitous in tourist restaurants is a coastal adaptation that Valencians regard with undisguised suspicion.",
  sport: "Spain's football national team won three consecutive major tournaments — Euro 2008, World Cup 2010, Euro 2012 — a tiki-taka dominance built on FC Barcelona's La Masia academy system and a generation of players including Xavi, Iniesta and Villa that transformed possession football into a tactical doctrine studied globally.",
  nature: "The Picos de Europa, in Asturias and Cantabria, rise to 2,650 metres from a coastline just 15 kilometres away — a compression of landscape so dramatic that it shapes local microclimates, produces a dense network of canyon walking routes, and supports the Iberian brown bear population in its last viable habitat."
},
"Sri Lanka": {
  capital: "Sri Jayawardenepura Kotte, built on the outskirts of Colombo in a 15th-century royal capital and reinstated as legislative seat in 1982, functions as Sri Lanka's constitutional capital while Colombo remains the commercial and practical centre — an administrative distinction that confuses visitors and occasionally Sri Lankans.",
  people: "Sri Lanka's tradition of Kandyan dance, originating in the rituals of the Natha Devale temple in Kandy and codified under the last Kandyan kings, involves elaborately costumed performers executing precise footwork for the Esala Perahera procession — a ten-day festival drawing over a million spectators.",
  sport: "Sri Lanka's 1996 Cricket World Cup victory — achieved as a team considered too small to compete, whose openers Sanath Jayasuriya and Romesh Kaluwitharana invented the modern batting powerplay by scoring at rates previously considered reckless — permanently changed how all nations approached the start of limited-overs innings.",
  nature: "Sri Lanka's central highlands, a World Heritage Site, contain the Horton Plains' dramatic World's End escarpment — a sheer 870-metre drop into the southern lowlands — and the cloud forests that produce Ceylon tea, a crop that reshaped the island's entire ecology and economy after coffee blight destroyed the previous plantation system in the 1870s."
},
"Sudan": {
  capital: "Khartoum sits at the confluence of the Blue and White Nile rivers — a meeting of waters so distinct in colour and temperature that they flow side by side without mixing for several kilometres — and the city's position at this junction has made it a trade and administrative node since the Ottoman period.",
  people: "Sudanese hospitality centres on the coffee ceremony, jebena buna, in which beans are roasted, ground and brewed in a clay pot before guests over a shared conversation that cannot be hurried — a ritual that structures social time in both urban apartments and rural villages.",
  food: "Ful Medames — slow-cooked fava beans with cumin, lemon and olive oil — is among the oldest continuously prepared dishes in the Nile Valley, with fava beans found in ancient Egyptian archaeological sites, and remains the essential breakfast of Sudan's cities, served from communal pots ladled into enamel bowls since before recorded hospitality.",
  sport: "Sudanese football has been shaped by the Al-Hilal and Al-Merrikh clubs of Khartoum, whose rivalry draws crowds comparable to national elections and whose continental campaigns in the CAF Champions League remain the primary vehicle through which Sudanese football identity reaches beyond its borders.",
  nature: "Sudan's Nubian Desert contains more ancient pyramids than Egypt — over 200 at the Meroe, Nuri and El-Kurru sites — built by the Kushite kingdoms between 700 BCE and 350 CE, the remnants of a civilisation so thoroughly overshadowed by its northern neighbour that its scale is still surprising to most visitors."
},
"Sweden": {
  capital: "Stockholm is built across 14 islands where Lake Mälaren meets the Baltic Sea, and Gamla Stan — the Old Town on its own island — contains a medieval street grid and the Baroque Royal Palace, whose 1,430 rooms make it the world's largest palace still in use by a reigning monarch.",
  people: "Sweden's Law of Jante, articulated by Danish-Norwegian author Aksel Sandemose in 1933 but recognised immediately as describing a real Scandinavian social code, discourages individual boastfulness and prizes collective modesty — an ethic that shapes corporate culture, political discourse and the social awkwardness of accepting a compliment.",
  sport: "Sweden produced Björn Borg, whose five consecutive Wimbledon titles between 1976 and 1980 and four French Opens in the same period made him the sport's first rock-star figure — and the ice hockey programme has been equally consistent, with the Tre Kronor winning seven World Championships since 1990.",
  nature: "Allemansrätten — the right to roam — is enshrined in Swedish law, granting every person the right to walk, camp and pick berries across any land, including private property, a legal tradition that has shaped a national relationship with forests and lakes fundamentally different from most of the property-conscious world."
},
"Switzerland": {
  capital: "Bern, the federal city since 1848, is neither the largest nor wealthiest Swiss city — that distinction belongs to Zurich and Geneva — but its six kilometres of arcaded sandstone walkways, medieval clock tower, and bear park in the river bend preserve a working capital of unusual human scale.",
  people: "Switzerland's four linguistic communities — German, French, Italian and Romansh — negotiate federal policy through a system of direct democracy in which citizens vote on federal referendums several times a year, producing a population with an unusually detailed civic literacy about policy trade-offs.",
  sport: "Roger Federer's 20 Grand Slam titles turned Switzerland, a country with a previous tennis tradition of approximately zero, into a nation that built a new indoor arena in Basel partly to ensure he could play there annually — and his three-set loss to Rafael Nadal in the 2008 Wimbledon final is still discussed as the finest match ever played.",
  nature: "The Swiss Alps contain over 1,800 named glaciers, but the Aletsch Glacier — 23 kilometres long and the largest in the Alps — has receded 3 kilometres since 1870, and its documented retreat has made it a primary case study in the visible measurement of climate change."
},
"Syria": {
  capital: "Damascus is among the world's oldest continuously inhabited cities, with settlement dating to the 3rd millennium BCE, and the Umayyad Mosque — built in 705 CE over a Byzantine cathedral that had replaced a Roman temple — compresses the city's layered history into a single building still in active use.",
  people: "Syrian craftspeople in the old souks of Damascus and Aleppo produced damask fabric, a weaving technique so identified with the city that the English language preserves the name — and the brocaded silk patterns developed there influenced European textile production for centuries after Crusader-era trade routes opened.",
  food: "Kibbeh — bulgur wheat casing around spiced lamb — is described as the national dish of several Levantine countries, but Syrian preparation, particularly the stuffed fried version from Aleppo and the raw kibbeh nayyeh of the coastal mountains, represents a technique refined over centuries in a region where grinding wheat and lamb together predates recorded cookbooks.",
  sport: "Syrian football club Al-Wahda Damascus, founded in 1928, has won the Syrian Premier League over 30 times and provided the backbone of a national team that reached the 2022 World Cup qualification play-offs — a competitive achievement made extraordinary by the fact that the squad trained across multiple countries during a decade of civil war.",
  nature: "The Syrian Desert's Palmyra oasis, surrounded by 520,000 square kilometres of steppe and sand, sustained one of the ancient world's most important caravan cities precisely because water existed where none should — a geological accident that built an empire and whose destruction by ISIS in 2015 made the fragility of deep history viscerally apparent."
},
"Tanzania": {
  capital: "Dodoma replaced Dar es Salaam as Tanzania's official capital in 1974 under Julius Nyerere's Ujamaa policy of decentralisation, though the coastal city remains the commercial centre — making Dodoma a planned capital still in the process of acquiring the institutions and population density to justify its designation.",
  people: "Swahili — KiSwahili — originated on Tanzania's coast from centuries of Arab, Persian and Bantu interaction and became the East African lingua franca not through colonial imposition but through trade networks: it is now the first African language to be added to the Google Assistant and Amazon Alexa platforms.",
  sport: "Tanzania's Kilimanjaro Marathon, run at altitude around the base of Africa's highest mountain each March, draws international runners to a course that combines competitive racing with the specific physiological challenge of 900 metres of altitude — and the local runners who dominate it train on the same slopes year-round.",
  nature: "Serengeti National Park hosts the largest terrestrial mammal migration on Earth — 1.5 million wildebeest and 250,000 zebra moving in a clockwise annual circuit across 30,000 square kilometres — a phenomenon driven by rainfall patterns that has continued for millions of years and is the defining image of African wilderness."
},
"Thailand": {
  capital: "Bangkok's official ceremonial name — Krung Thep Maha Nakhon — is an abbreviation of a 169-character full name given by Rama I in 1782, and the city's Grand Palace complex, built in the same year on a bend of the Chao Phraya River, remains the spiritual and symbolic centre of the Thai monarchy.",
  people: "Thai social interaction is governed by the concept of kreng jai — the desire to avoid burdening or discomforting another person — which produces indirect communication, reluctance to say no directly, and a hospitality so insistent that refusal of food or an offer of help requires careful social navigation.",
  sport: "Muay Thai — the art of eight limbs, using fists, elbows, knees and shins — has been practised in Thailand for at least 500 years; the Rajadamnern and Lumpinee stadiums in Bangkok host weekly bouts that retain a ceremonial pre-fight dance, the Wai Kru, unchanged for generations.",
  nature: "Phang Nga Bay in southern Thailand contains over 40 limestone karst towers rising vertically from the Andaman Sea — including Ko Tapu, the isolated pinnacle made internationally known by its appearance in The Man with the Golden Gun — a seascape created by rising sea levels flooding a karst landscape 12,000 years ago."
},
"Turkey": {
  capital: "Ankara was chosen as Turkey's capital by Mustafa Kemal Atatürk in 1923 specifically because it lay in the Anatolian heartland rather than the cosmopolitan Ottoman Istanbul — a deliberate statement that the new republic would be built from the interior out, and the Anıtkabir mausoleum, where Atatürk is interred, receives over 10 million visitors annually.",
  people: "Çay — black tea brewed in a double-stacked kettle and served in tulip-shaped glasses — is consumed at a rate of 3.5 kilograms per person per year, making Turkey the world's highest per-capita tea consumer, and the tea house, the çay evi, functions as the primary venue for male social life across the country's smaller cities and villages.",
  food: "Döner Kebab's rotating spit was developed in 19th-century Bursa, where chef Hacı İskender Efendi is credited with inventing the horizontal stacking method around 1860 — the Turkish original, served over bread with tomato sauce and browned butter, bears little resemblance to the Berlin döner that German-Turkish migrants transformed into Europe's most consumed street food.",
  sport: "Turkish oil wrestling, Yağlı Güreş, practised since the 14th century at the Kırkpınar tournament in Edirne — the world's oldest continuously running sporting competition — involves wrestlers covering themselves in olive oil and competing without a time limit, an event that has continued uninterrupted since 1362.",
  nature: "Cappadocia's fairy chimneys — volcanic tuff columns sculpted by differential erosion over millions of years — were hollowed into cave churches, monasteries and underground cities by Byzantine-era communities, some descending eleven storeys beneath the surface, and the landscape at dawn, covered in hot-air balloons, has become one of the world's most replicated travel images."
},
"Uganda": {
  capital: "Kampala is built across seven hills — a topography that mirrors Rome's and was noted by early British administrators — and the city's Kasubi Tombs, the burial site of four Buganda Kingdom kabakas, represent the most significant royal architectural site in East Africa, constructed entirely from organic materials.",
  people: "Uganda's Buganda Kingdom, the largest of the traditional kingdoms now operating within the republic, maintains its own parliament, cultural institutions and kabaka — creating a parallel cultural governance structure that the national government has negotiated rather than eliminated.",
  sport: "Uganda's distance running tradition — shaped by highland altitude training around the Rwenzori foothills — produced Stephen Kiprotich's 2012 Olympic marathon gold in London, Uganda's first Olympic track and field medal in 40 years.",
  nature: "Bwindi Impenetrable National Park, a highland rainforest in southwestern Uganda, contains approximately half the world's remaining mountain gorilla population — around 460 individuals — in forest so dense that early explorers named it for its near-impassability, and permits to track gorilla families are allocated by lottery months in advance."
},
"Ukraine": {
  capital: "Kyiv's Pechersk Lavra — the Monastery of the Caves — was founded in 1051 on limestone bluffs above the Dnipro River and contains a network of underground tunnels where the mummified remains of medieval monks are displayed by candlelight; the monastery complex is a World Heritage Site and the spiritual origin point of Eastern Orthodox Christianity as practised across Russia and the Slavic world.",
  people: "Ukrainians maintain a tradition of pysanky — Easter eggs decorated using a wax-resist method with geometric and symbolic patterns specific to each region — a practice pre-dating Christianity that was nearly suppressed in the Soviet period and has undergone a pronounced revival as an act of cultural assertion since 2014.",
  sport: "Vitali and Wladimir Klitschko held all four major heavyweight boxing world titles simultaneously between 2004 and 2015, an era of dominance so complete that the heavyweight division was effectively a Ukrainian property — and both brothers later became mayors of Kyiv, translating boxing fame into civic authority.",
  nature: "The Carpathian Mountains in western Ukraine contain the largest primeval beech forest in Europe, a UNESCO World Heritage Site shared with Slovakia and Romania, and the Dnipro River — which bisects the country north to south — has shaped Ukrainian settlement, agriculture and identity as fundamentally as the Nile shaped Egypt."
},
"United Kingdom": {
  capital: "London has been continuously occupied since Roman Londinium was founded around 50 CE, and the City of London — the original square mile — still operates under a medieval corporation with its own Lord Mayor, separate from the wider London mayor, governing a financial district whose legal architecture predates Parliament.",
  people: "British understatement is not merely a conversational style but a codified social technology: the phrase 'not bad' signals genuine enthusiasm, 'quite good' is moderate praise, and 'interesting' usually means the opposite — a system that functions perfectly within the culture and baffles everyone outside it.",
  food: "Fish and Chips emerged as a working-class staple in the industrial north and east of England in the 1860s, when railway refrigeration made fresh sea fish available inland for the first time — by 1910 there were 25,000 chip shops across the country, feeding factory workers on Friday pay nights.",
  sport: "England invented association football, codified it at a Cambridge pub meeting in 1863, exported it to every corner of the globe, and then waited 103 years to win a World Cup — the 1966 triumph at Wembley, sealed by Geoff Hurst's hat-trick, remains the national sporting reference point against which everything else is measured.",
  nature: "The Scottish Highlands contain Europe's most extensive sub-arctic plateau in the Cairngorms, a landscape of ancient Caledonian pine forest, ptarmigan, red squirrel and osprey, shaped by ice sheets that retreated only 10,000 years ago and now one of the last places in Britain where the land has not been fundamentally altered by agriculture."
},
"United States of America": {
  capital: "Washington D.C. was designed by French military engineer Pierre Charles L'Enfant in 1791 on a diagonal grid overlaid onto a rectilinear street plan, with the Capitol building placed on the highest point — a layout conceived to make the legislature visually dominant over the executive branch and still legible in the city's geography today.",
  people: "Americans built the world's most durable civic religion around their founding documents — the Declaration of Independence and Constitution are displayed behind bulletproof glass in the National Archives as secular scripture — and the practice of political self-reinvention, the idea that identity is chosen rather than inherited, remains the country's most exported cultural product.",
  sport: "The Super Bowl, played each February, is the most-watched annual television event in American history — and the game itself is almost secondary to the halftime show and advertising market, with 30-second commercial slots exceeding $7 million, a commercialisation of sport so total that it has become its own cultural phenomenon.",
  nature: "The Colorado River carved the Grand Canyon to a depth of 1,800 metres over six million years, exposing 2-billion-year-old basement rock and creating a geological cross-section of North American time that the Havasupai people have inhabited for 800 years — and whose course has been so heavily dammed that it no longer reliably reaches the sea."
},
"Uruguay": {
  capital: "Montevideo's Old City retains the grid of its 1726 Spanish colonial founding, and its Mercado del Puerto — a 19th-century iron market hall built for the port — now houses parrilla restaurants where the open charcoal grills burn wood from the Uruguayan interior, a lunch ritual that stockbrokers and dock workers attend in equal numbers.",
  people: "Uruguay became the first country in the world to fully legalise recreational cannabis, in 2013 under President José Mujica — a former Tupamaros guerrilla who served 14 years in solitary confinement and then governed from a small farm, donating 90 percent of his presidential salary to charity.",
  food: "The Chivito was invented in Montevideo in 1944 when a restaurant owner, unable to supply a customer who asked for goat meat, improvised with beef steak, ham, bacon, egg and cheese in a roll — and the resulting sandwich became Uruguay's national snack, sold from beachfront kiosks along the entire Río de la Plata coast.",
  sport: "Uruguay won the inaugural FIFA World Cup on home soil in 1930 and repeated it in Brazil in 1950 — the Maracanazo, their 2–1 defeat of Brazil in the Maracanã before 200,000 people, is still described in Brazil as 'the greatest national tragedy' — achievements extraordinary for a country whose entire population is smaller than many of the cities it defeated.",
  nature: "Uruguay's landscape is almost entirely Pampas grassland — the Campos — rolling hills without the dramatic peaks or canyons of its neighbours, a geography that made cattle ranching the economic and cultural foundation of the nation and produced the gaucho tradition of horseback herding that persists on working estancias."
},
"Uzbekistan": {
  capital: "Tashkent was largely destroyed by a 1966 earthquake and rebuilt by Soviet planners who created wide Brutalist boulevards — but the Chorsu Bazaar, a domed market operating continuously since the medieval period, survived, and the city now navigates an identity between Soviet monumentalism and the Silk Road heritage the government is actively restoring.",
  people: "Uzbeks celebrate Navruz, the Persian New Year on the spring equinox, with sumalak — a paste made by cooking germinated wheat sprouts for 24 hours while community members take turns stirring the cauldron and making wishes — a communal cooking act that functions as neighbourhood social contract.",
  sport: "Uzbekistan has won more Olympic wrestling medals per capita than almost any other nation — Artur Taymazov took three consecutive freestyle wrestling golds between 2000 and 2008, and the country's combat sports academies, built during the Soviet period, continue to produce Greco-Roman and freestyle champions at World Championship level.",
  nature: "The Aral Sea, once the world's fourth-largest lake, has shrunk to 10 percent of its original size since Soviet-era irrigation diverted its feeder rivers to cotton fields — the rusted ships stranded in what is now the Aralkum Desert near Muynak constitute the most visible ecological catastrophe of the 20th century."
},
"Venezuela": {
  capital: "Caracas sits in a narrow valley at 900 metres altitude just 40 kilometres from the Caribbean coast — a geography that produces a spring-like climate year-round despite its tropical latitude — and the city's 1960s modernist architecture, commissioned during the oil boom, includes Carlos Raúl Villanueva's University City, a UNESCO World Heritage Site integrating murals by Alexander Calder and Fernand Léger.",
  people: "Venezuela has won more Miss Universe and Miss World titles than any other country — a record 8 Miss Universe and 6 Miss World crowns — producing a beauty pageant industry with professional academies, nationwide televised competitions and a cultural status that makes pageant winners as recognisable as football players.",
  sport: "Venezuelan baseball sent Miguel Cabrera to the major leagues — a player who achieved the first Triple Crown since 1967 in 2012 — and the country has produced over 300 MLB players, making the sport not merely a pastime but an export industry, with academies funded by major league teams operating across the Llanos region.",
  nature: "Angel Falls in Canaima National Park drops 979 metres in an uninterrupted cascade from the top of Auyán-tepui, a sandstone tabletop mountain — the world's highest waterfall, fed by cloud forest so consistently mist-covered that the tepui summits constitute isolated ecological islands that evolved independently from the lowlands below."
},
"Vietnam": {
  capital: "Hanoi, Vietnam's capital since reunification in 1976, preserves the French colonial urban fabric of its Old Quarter — 36 streets each historically named for the guild that traded there — alongside the Ba Dinh Square where Ho Chi Minh read the Declaration of Independence in 1945, a city where 1,000 years of Chinese administration, 80 years of French colonialism and 30 years of warfare all left visible archaeology.",
  people: "Vietnamese coffee culture evolved from French colonial introduction of arabica cultivation in the late 19th century into something entirely distinct: cà phê trứng — egg coffee, beaten with condensed milk into a custard-like foam — was invented in Hanoi in the 1940s as a substitute for scarce fresh milk and remains the city's most specific culinary identity.",
  food: "Phở originated in the Red River Delta region of northern Vietnam in the early 20th century, likely shaped by Chinese and French culinary contact — the long-simmered bone broth, rice noodles and herbs were sold from street carts and became the breakfast of Hanoi workers before the dish migrated south with the 1954 partition and transformed into the sweeter, garnish-heavy Ho Chi Minh City version.",
  sport: "Vietnam's 2008 AFF Championship victory — the national football team's first major regional title — produced street celebrations in Hanoi and Ho Chi Minh City that shut traffic for hours, and the 2019 AFC U23 Championship runner-up finish under South Korean coach Park Hang-seo sparked a generational renewal of football passion not seen since the war generation.",
  nature: "Ha Long Bay contains over 1,600 limestone karst islands rising from the Gulf of Tonkin, a seascape so dramatic that it appears on the Vietnamese 200,000-dong banknote — the islands' caves, including Hang Đầu Gỗ, which concealed a Vietnamese fleet's iron-tipped stakes before the 1288 defeat of Kublai Khan's armada, layer military history over geological spectacle."
},
"Yemen": {
  capital: "Sana'a's Old City is one of the world's most architecturally distinct urban centres — multi-storey tower houses built from dark volcanic stone with elaborate white gypsum geometric friezes, a building tradition 2,500 years old that UNESCO recognised in 1986 and that remains inhabited by families whose tenure extends further back than most nations' written histories.",
  people: "The qat afternoon — the daily practice of chewing qat leaves in social gatherings called mafraj sessions, held in the upper floors of tower houses — structures Yemeni male social life from roughly 2pm onward, consuming an estimated 40 percent of the country's agricultural water and functioning as an irreplaceable social institution regardless of economic conditions.",
  sport: "Yemeni football has been shaped by the Al-Ahly Sana'a and Sha'ab Ibb clubs, whose rivalry predates the civil conflict, and the national team's participation in Gulf Cup competitions has historically been the primary vehicle for maintaining a sporting identity through repeated periods of political instability.",
  nature: "Socotra Island, 240 kilometres off the Yemeni coast, is so geographically isolated that 37 percent of its plant species exist nowhere else on Earth — including the Dragon Blood Tree, whose umbrella-shaped canopy and red resin produce a landscape so alien that NASA scientists have used it to test instruments designed for other planets."
},
"Zimbabwe": {
  capital: "Harare was founded as Fort Salisbury in 1890 by the British South Africa Company's Pioneer Column and was renamed at independence in 1980 after a Shona chief — Neharawa, meaning 'he who does not sleep' — and the National Gallery of Zimbabwe, opened in 1957, houses one of the continent's most significant collections of stone sculpture from the Shona school.",
  people: "Zimbabwe's stone-carving tradition — Shona sculpture — emerged in the 1950s when artist Frank McEwen encouraged local artists to work with the country's abundant verdite and springstone, producing a school of modernist figurative sculpture that reached major international galleries in London and New York within a decade.",
  sport: "Zimbabwe's cricket team produced Henry Olonga and Andy Flower, who wore black armbands at the 2003 World Cup to mourn 'the death of democracy in Zimbabwe' — one of sport's most deliberate political statements, delivered at the risk of prosecution and later exile, by players who prioritised conscience over career.",
  nature: "Victoria Falls — Mosi-oa-Tunya, 'the smoke that thunders' in Tonga — spans 1,708 metres across the Zambezi River gorge and produces a spray cloud visible 50 kilometres away; David Livingstone became the first European to see it in 1855 and described it as a sight 'so lovely it must have been gazed upon by angels'."
},
"Zambia": {
  capital: "Lusaka grew from a railway siding named after a local headman, Lusakasa, into a national capital at independence in 1964 — its National Museum documents the entire arc from Iron Age settlement to Kenneth Kaunda's founding presidency, and the city's position at the juncture of four provinces reflects Zambia's deliberate postcolonial geography.",
  people: "Zambia's 73 recognised ethnic groups coexist within a national identity shaped by Kenneth Kaunda's Humanism philosophy — an African socialist doctrine emphasising reconciliation over retribution — and the country is notable in the region for peaceful transfers of power, having held competitive multiparty elections since 1991.",
  sport: "The 1993 Gabon air crash killed the entire Zambian national football squad — 18 players and 12 officials — in a disaster that ended one of Africa's most promising football generations, and the 2012 Africa Cup of Nations victory, won on penalties in Libreville — the city nearest the crash site — was experienced across Zambia as a completion of unfinished history.",
  nature: "The Kafue National Park, at 22,400 square kilometres, is one of the largest in Africa and one of the least visited — its Busanga Plains flood seasonally to create a vast wetland supporting enormous herds of red lechwe, lions, wild dog and cheetah, in a landscape whose inaccessibility has preserved an ecosystem largely unchanged from its pre-colonial state."
},
"Armenia": {
  capital: "Yerevan, one of the world's oldest continuously inhabited cities, was built in its modern form by Soviet architect Alexander Tamanian in the 1920s using pink tuff stone quarried from the surrounding volcanic plateaus — and the Cascade complex of terraced gardens and staircases ascending the northern hills contains one of the Caucasus's most significant collections of contemporary art.",
  people: "Armenians maintain one of the world's most diaspora-conscious identities — the 1915 Genocide dispersed Armenian communities to Lebanon, France, Argentina and California, and the descendants of those communities have sustained language schools, churches and political advocacy organisations across a century of displacement.",
  sport: "Armenian wrestling traces an unbroken tradition through Greco-Roman competition — Artur Aleksanyan has won consecutive Olympic gold medals at Rio 2016 and Tokyo 2020, and the country's combat sports culture produces world champions in boxing, sambo and judo at a rate disproportionate to its 3-million population.",
  nature: "Mount Ararat — the snow-capped volcanic massif visible from Yerevan and featured on the national coat of arms — lies entirely within Turkey following the 1921 Treaty of Kars, making the defining natural symbol of Armenian identity a daily view of foreign-held land, a geographic wound that structures national consciousness."
},
"Azerbaijan": {
  capital: "Baku's Old City, Icherisheher, contains the 12th-century Maiden Tower and Shirvanshah's Palace behind medieval walls — immediately adjacent to the Flame Towers, three glass skyscrapers whose LED facades animate as fire visible across the Caspian — a city where every other building represents a different century of Azerbaijani ambition.",
  people: "Azerbaijan's carpet-weaving tradition is one of the oldest in the world, with regional pile carpet designs from Karabakh, Shirvan and Guba so distinct that experts can identify provenance to within 50 kilometres — and the 2010 UNESCO designation of Azerbaijani carpet weaving as Intangible Cultural Heritage codified what weavers' families had always understood as a complete language of symbols.",
  sport: "Azerbaijan has built a combat sports infrastructure of unusual depth — and the hosting of the inaugural 2015 European Games in Baku signalled a country using sport as a primary instrument of international visibility.",
  nature: "The Absheron Peninsula on the Caspian coast hosts natural petroleum seeps that have burned continuously for millennia — the Yanar Dag fire has likely burned since ancient times and drew Zoroastrian fire worshippers from across the ancient world, making Azerbaijan's underground oil reservoirs a geological fact that shaped both its economy and its pre-Islamic spiritual identity."
},
"Bahrain": {
  capital: "Manama's Bahrain Fort — Qal'at al-Bahrain — is a UNESCO World Heritage Site containing archaeological layers from the Dilmun civilisation of 2300 BCE through to Portuguese occupation in the 16th century, making this small capital city the site of one of the most compressed stratigraphic records of Gulf trading history.",
  people: "Bahrain's pearl diving tradition — hamat al-ghaws — defined the archipelago's economy for over 2,000 years until Japanese cultured pearls collapsed the market in the 1930s, and the songs sung by divers during the descent, the fidjeri, are maintained by UNESCO-recognised ensembles as one of the Gulf's most specific oral musical traditions.",
  sport: "The Bahrain Grand Prix, held at the Sakhir Circuit since 2004, introduced Formula One to the Middle East and has served as the season-opening race multiple times — the circuit's outer 'endurance' layout hosted the first night race in F1 history in 2014, and Bahrain's investment in motorsport infrastructure made it the regional model for subsequent Saudi and Abu Dhabi race bids.",
  nature: "The Hawar Islands, a Bahraini archipelago in the Gulf just off the Qatari coast whose sovereignty was disputed in a 30-year ICJ case finally settled in 2001, support the second-largest breeding colony of the Socotra cormorant on Earth — a seabird whose mass nesting involves hundreds of thousands of individuals."
},
"Bahamas": {
  capital: "Nassau grew from a British colonial settlement on New Providence Island in the late 17th century, a haven first for pirates — including Blackbeard and Charles Vane who used its harbour in the early 1700s — and later for Loyalists fleeing the American Revolution, whose plantation architecture survives in the pink colonial buildings of Bay Street.",
  people: "Junkanoo — the Bahamian street festival celebrated on Boxing Day and New Year's Day — involves months of secret costume-building by competing groups, culminating in all-night parades of feathered and beaded constructions weighing over 50 kilograms worn by dancers moving to goatskin drums and cowbells, a tradition with roots in West African masquerade that survived enslavement in Caribbean form.",
  sport: "The Bahamas has produced Olympic sprint champions entirely disproportionate to its 400,000 population — Frank Rutherford, Pauline Davis and the relay teams that won gold at Athens 2004 — and the islands' per-capita Olympic medal count in athletics rivals that of Jamaica, sustained by a culture in which school track meets are the country's primary sporting spectacle.",
  nature: "The Andros Barrier Reef, the third-largest coral reef system in the world, runs 225 kilometres along the eastern edge of Andros Island, dropping into the Tongue of the Ocean — a submarine trench plunging 1,800 metres that the US Navy has used as an underwater testing range, the deepest and most abrupt transition from reef to abyss in the Atlantic."
},
"Barbados": {
  capital: "Bridgetown, founded in 1628, contains the Garrison Savannah — a 19th-century British military complex now used as a horse racing track — and the Parliament Buildings of 1874, making it one of the Caribbean's oldest legislative bodies in continuous operation, housed in a Gothic Revival structure that looks transplanted from Westminster.",
  people: "Barbadians, Bajans, maintain a culture of extraordinary literary production for an island of 280,000 — George Lamming's In the Castle of My Skin and Kamau Brathwaite's poetry are studied in British and American universities, a tradition rooted in the same Eastern Caribbean literary culture that produced Nobel laureate Derek Walcott.",
  sport: "Sir Garfield Sobers, born in Bridgetown in 1936, is considered the greatest all-round cricketer in history — his 1958 world record Test score of 365 not out stood for 36 years, and his 1968 feat of hitting six consecutive sixes in a first-class over remains one of cricket's defining statistical moments.",
  nature: "Barbados is entirely underlain by coral limestone — there is no volcanic rock, unlike most Caribbean islands — and this geology produces an extraordinary network of caves, including Harrison's Cave with its active stalactite formations, while the porous limestone filters rainwater into underground aquifers that have supplied the island since pre-Columbian Arawak settlement."
},
"Belarus": {
  capital: "Minsk was almost entirely destroyed in World War II — the city lost over 80 percent of its structures — and was rebuilt as a Stalinist showcase with triumphal axial boulevards, colonnade-fronted ministry buildings and the vast Independence Square, producing an urban landscape that is one of Soviet architecture's most complete surviving ensembles.",
  people: "Belarusians maintain a tradition of oral folk magic, zamovy — incantations for healing, protection against bad luck, and appeasing natural forces — recorded by ethnographers as late as the 20th century and still practised in rural villages alongside Orthodox Christianity, a syncretic combination the church officially discourages but has never fully suppressed.",
  sport: "Belarus's ice hockey team defeated Sweden and Finland to reach the 2002 Salt Lake City Olympic final, a result so unexpected it is referred to domestically as the Miracle on Ice, and the country's hockey league exports players regularly to the KHL and has produced Alex Ovechkin's contemporaries.",
  nature: "Belovezhskaya Pushcha, the Belarusian portion of the Białowieża Forest shared with Poland, is the largest surviving fragment of the primeval mixed forest that once covered the European Plain — and it was in the Viskuli government hunting lodge within the forest that the Soviet Union was formally dissolved on December 8, 1991."
},
"Belize": {
  capital: "Belmopan was built from scratch after Hurricane Hattie destroyed 75 percent of the former capital Belize City in 1961 — the government commissioned a new inland capital on the Belize River, designed with a Maya archaeological site's layout as inspiration, making it one of the few purpose-built capitals in the Americas.",
  people: "Belize is the only Central American country whose majority language is English and whose culture is more Caribbean than Latin — its Garifuna population, descendants of Afro-Caribbean and Arawak people exiled from St Vincent by the British in 1797, maintain a language and drum music tradition that UNESCO listed as Intangible Cultural Heritage in 2001.",
  sport: "Belize's basketball culture coexists with football as the sport where Belizean athleticism is most visible regionally — and the country's Caribbean Games athletics programme has produced sprinters competitive at the CARIFTA level.",
  nature: "The Belize Barrier Reef, at 300 kilometres the longest in the Northern Hemisphere, contains the Great Blue Hole — a circular marine sinkhole 300 metres across and 125 metres deep, formed when a limestone cave system collapsed as sea levels rose after the last ice age — a formation that Jacques Cousteau ranked among the world's top dive sites in 1971."
},
"Benin": {
  capital: "Porto-Novo, Benin's official capital, sits in the shadow of Cotonou, the far larger commercial city — the city's 19th-century Brazilian-style architecture, built by returning former slaves, gives it a distinctive streetscape unlike any other West African capital.",
  people: "Benin is the birthplace of Vodoun — the original Fon and Ewe animist tradition of communicating with intermediary spirits that was carried across the Atlantic by enslaved people and transformed in the Americas — and the annual Vodoun Festival in Ouidah, held each January, draws practitioners from Brazil, Cuba and Haiti back to the source.",
  sport: "Benin's football development has been shaped by the Squirrels' qualification for the 2019 Africa Cup of Nations round of 16 — eliminating Morocco in the process — a result that generated the country's most significant football celebration since independence.",
  nature: "The Pendjari National Park in northern Benin is part of the W-Arli-Pendjari transboundary complex, one of West Africa's last intact large mammal ecosystems, home to elephants, lions, hippopotamuses and West African cheetahs — a wildlife conservation area whose continued viability depends on cross-border management agreements between Benin, Burkina Faso and Niger."
},
"Bhutan": {
  capital: "Thimphu is one of the world's few capitals with no traffic lights — roundabouts manage flow, and the one occasion a traffic light was installed it was removed following citizen complaints that it felt impersonal — and the city's architecture is governed by a law requiring all new buildings to incorporate traditional Bhutanese dzong design elements.",
  people: "Bhutan measures national success through Gross National Happiness — a development philosophy formalised by King Jigme Singye Wangchuck in the 1970s that balances economic growth against cultural preservation, environmental sustainability and good governance — an approach that the UN has studied but no other country has formally adopted as constitutional policy.",
  sport: "Archery is Bhutan's national sport and differs from Olympic archery in every social dimension — bouts are community events involving singing, dancing and deliberate distraction of opponents by teammates standing near the target, and the traditional bamboo bow has been largely replaced by compound bows while the ceremonial format remains unchanged.",
  nature: "Bhutan has constitutionally mandated that a minimum of 60 percent of its land area must remain under forest cover in perpetuity — currently over 70 percent is forested — and the country is carbon negative, absorbing three times more CO2 than it produces, making it the only country where the ecological constraint is written into the founding law."
},
"Bosnia and Herzegovina": {
  capital: "Sarajevo was besieged for 1,425 days between 1992 and 1996 — the longest siege of a capital city in the history of modern warfare — and the city today contains a dedicated Tunnel of Hope Museum beneath a private house through which food and weapons were smuggled under the airport runway during the encirclement.",
  people: "Sarajevo's Baščaršija quarter — the 15th-century Ottoman bazaar district — contains a Catholic cathedral, Orthodox church, mosque and synagogue within 500 metres of each other, a proximity that has been called the Jerusalem of Europe and that represents both the city's historic coexistence and the specific reason it became the target of forces who found that coexistence intolerable.",
  sport: "Bosnia and Herzegovina's 2014 World Cup qualification — the country's first since independence in 1992 — was achieved with Edin Džeko and Miralem Pjanić leading a squad that became a vehicle for post-war national cohesion, and their opening tournament win over Argentina in Group F produced celebrations in Sarajevo that the city compared to liberation.",
  nature: "The Sutjeska National Park in southeastern Bosnia contains Perućica, one of Europe's last two remaining primeval rainforests — a relict Holocene forest of 3,000-year-old beech and fir trees covering 1,434 hectares in a river canyon so remote that it was not systematically surveyed until the 1950s."
},
"Botswana": {
  capital: "Gaborone was built from nothing in 1964, three years before independence, on the edge of the South African border — the choice of a new site rather than an existing town reflected the government's desire for a capital uncontaminated by colonial-era racial geography — and today its diamond-funded growth has made it one of southern Africa's most stable and prosperous cities.",
  people: "Botswana's Tswana tradition of Kgotla — a public assembly open to all adults, historically held under a tree where community decisions were debated until consensus — was incorporated into the country's post-independence governance as a formal consultative mechanism, making it one of Africa's earliest examples of indigenous democratic institution integration.",
  sport: "Isaac Makwala's 200m and 400m double at the 2017 World Athletics Championships in London — achieved after he was controversially barred from the 200m heats due to illness, reinstated after a solo time trial, and then ran his semi-final and final within hours — produced one of the championships' most dramatic performances and Botswana's most celebrated individual athletic moment.",
  nature: "The Okavango Delta — an inland river that flows from Angola into the Kalahari Desert and simply stops, spreading into 15,000 square kilometres of seasonal floodplain without ever reaching the sea — creates one of the world's most biodiverse ecosystems in the middle of southern Africa's driest region, a hydrological accident that produced a UNESCO World Heritage Site."
},
